### ISSUE TITLE
Hierarchical Clustering Index with Hamming Distance

### ISSUE THREAD

**Issue by tejus-gupta** [wildart/FLANN.jl#15]
FLANN provides hierarchical clustering index that can be used for matching binary features. Why is this now working?
```
d=Matrix{UInt8}(3, 5)
f=flann(d, FLANNParameters(algorithm=FLANN.FLANN_INDEX_HIERARCHICAL), FLANN.FLANN_DIST_HAMMING, 2)

t=Vector{UInt8}(3);
nearest(f, t, 1)
```

**Comment by wildart** [comment]
Distances FLANN_DIST_HAMMING, FLANN_DIST_HAMMING_LUT, FLANN_DIST_HAMMING_POPCNT, and FLANN_DIST_L2_SIMPLE are not supported through C bindings. So, no way to wrap them for usage in Julia (without Cxx).
